server {
    # écoute sur le port 443 en IPv4 IPv6 en mode SSL
    listen 443 ssl;
    listen [::]:443 ssl;

    # nom de domaine
    server_name mchemari.42.fr;

    # protocoles TLS obligatoire
    ssl_protocols TLSv1.2 TLSv1.3;

    # la ou on va generer les clés de chiffrement
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    # racine du site
    root /var/www/html;
    # ordre de recherche des fichiers index
    index index.php index.html index.htm;

    # on renvoi le fichier demande par le user sil existe sinon erreur 404
    location / {
        try_files $uri $uri/ =404;
    }

    # passerelle fastCGI pour envoyer le php a wordpress
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;

        # On envoie la requête PHP au conteneur wordpress sur le port 9000
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;

        # Paramètre indispensable pour que PHP-FPM sache quel fichier exécuter
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
