services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    networks:
      - inception_net
    secrets:
      - db_password
      - db_root_password

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mchemari/data/mariadb

networks:
  inception_net:
    driver: bridge

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
